### PR TITLE
Require correct binary builds to release

### LINKED ISSUE #155: Warn or don't remove package if the version being released isn't built
The build was failing, but this should not happen given `kernelstub` was still in `sync`. Did https://github.com/pop-os/repo-release/pull/151 somehow break things?

The version previously available was still in `pool`, but not `dists`.

As of https://github.com/pop-os/repo-release/pull/154, this is no longer an issue, but this shouldn't be possible so we should find the root cause.

### PR DESCRIPTION
**Pull request by 13r0ck**
A package must now build for all architectures in its `debian/control` file to be released. If not, a yellow warning is printed in the console, and the sync is skipped.

This is done by checking the architectures that that the package builds for, then checking if that package shows up in each binary `Packages` file. A small quirk is the filename is checked for, because the build script only gives us access to the git reponame, not the build package name. But there should never be a conflict there anyway.

Out build server only properly builds on amd64 and arm64, so we filter to only test those architectures at most.

Closes #155

### CODE REVIEW

**Comment by jackpot51** [comment]
Please wait for my specific review

File: build.sh [hunk 1]
```diff
@@ -23,6 +23,11 @@ ARCHS=(
     arm64
     src
 )
+# Architectures we want to guarentee built (currently our build server doesn't build i386)
```
Comment (jackpot51) [inline build.sh:26]: Our build server does build i386 for a number of packages, and it is important these never go away or else packages like steam and wine will not install correctly.

Comment (13r0ck) [reply build.sh:26]: hmm, some packages that were specified to linux-any haven't been building for i386

Comment (13r0ck) [reply build.sh]: This is now fixed in https://github.com/pop-os/repo-release/pull/194/commits/23346347031f2a22ae4936d8ea10cdea905953c2

I also added a flag to ignore the binary check https://github.com/pop-os/repo-release/pull/194/commits/0f12649e1cda69f162e494f8f242b7761c3820cb

**Review by jackpot51 — APPROVED** [review]

**Review by leviport — APPROVED** [review]
I ran a repo release on this branch without committing, and it looks like it's working well.
